name: Docker Image CI
on: push
jobs:
  push_to_registries:
    name: Push Docker Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [7.0, 7.1, 7.2, 7.3, 7.4]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: push to docker hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ytaku/php-cli:${{ matrix.version }}
          tag_with_ref: true

      - name: push to ghcr.io
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          registry: ghcr.io
          repository: taku-yamashita/php-cli:${{ matrix.version }}
          tag_with_ref: true
