name: Test
on: push
jobs:
  test_image:
    name: Test Docker Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [7.1, 7.2, 7.3, 7.4]
        composer_version: [v1, v2]
    steps:
      - name: checkout branch
        uses: actions/checkout@v2

      - name: build image
        run: docker build .
          --build-arg PHP_VERSION=${{ matrix.version }}
          --build-arg COMPOSER_VERSION=${{ matrix.composer_version }}
          -t ytaku/php-cli:${{ matrix.version }}-${{ matrix.composer_version }}

      - name: test
        run: |
          docker run --rm ytaku/php-cli:${{ matrix.version }}-${{ matrix.composer_version }} -v
          test $(docker run --rm ytaku/php-cli:${{ matrix.version }}-${{ matrix.composer_version }} -v | \
          awk 'NR==1' | awk -F ' ' '{print $2}' | awk -F '.' '{print $1"."$2}') = ${{ matrix.version }}
